from django.urls import path
from .recordings import (
    get_all_videos, list_all_videos_detailed,
    get_video_by_id, update_video, delete_video, stream_video,
    handle_document, view_mindmap, get_subtitles,
    Start_Recording, Stop_Recording,
    upload_recording, upload_recording_blob, upload_single_file,
    start_recording_with_metadata, stop_recording_and_finalize,
    get_recording_status,
    move_video_to_trash, list_trash_videos,
    restore_video, permanent_delete_video,
    store_custom_recording_name,
    get_transcript_content, get_summary_content,
)

urlpatterns = [
    path('api/videos/lists', get_all_videos, name='get_all_videos'),
    path('api/videos/list-detailed', list_all_videos_detailed, name='list_all_videos_detailed'),
    path('api/videos/<str:id>', get_video_by_id, name='get_video_by_id'),
    path('api/videos/update/<str:id>', update_video, name='update_video'),
    path('api/videos/remove/<str:id>', delete_video, name='delete_video'),
    path('api/videos/stream/<str:id>', stream_video, name='stream_video'),
    path('api/videos/document/<str:id>/<str:doc_type>', handle_document, name='handle_document'),
    path('api/videos/<str:id>/mindmap', view_mindmap, name='view_mindmap'),
    path('api/videos/<str:id>/subtitles/<str:lang>', get_subtitles, name='get_subtitles'),
    path('api/meetings/<str:id>/start-recording', Start_Recording, name='Start_Recording'),
    path('api/meetings/<str:id>/stop-recording', Stop_Recording, name='Stop_Recording'),
    path('api/videos/upload-recording', upload_recording, name='upload_recording'),
    path('api/recordings/upload-blob', upload_recording_blob, name='upload_recording_blob'),
    path('api/upload-single/', upload_single_file, name='upload_single_file'),
    path('api/recordings/start-with-metadata/<str:id>', start_recording_with_metadata, name='start_recording_with_metadata'),
    path('api/recordings/stop-and-finalize/<str:id>', stop_recording_and_finalize, name='stop_recording_and_finalize'),
    path('api/recordings/status/<str:meeting_id>', get_recording_status, name='get_recording_status'),
    path('api/recordings/trash/<str:id>', move_video_to_trash, name='move_video_to_trash'),
    path('api/videos/trash/list', list_trash_videos, name='list_trash_videos'),
    path('api/videos/restore/<str:id>', restore_video, name='restore_video'),
    path('api/videos/permanent-delete/<str:id>', permanent_delete_video, name='permanent_delete_video'),
    path('api/recordings/store-custom-name', store_custom_recording_name, name='store_custom_recording_name'),
    path('api/videos/transcript-content/<str:id>', get_transcript_content, name='get_transcript_content'),
    path('api/videos/summary-content/<str:id>', get_summary_content, name='get_summary_content'),
]