# Generated by Django 5.0.14 on 2025-06-26 06:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_name', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_type', models.CharField(blank=True, choices=[('CalendarMeeting', 'CalendarMeeting'), ('ScheduleMeeting', 'ScheduleMeeting'), ('InstantMeeting', 'InstantMeeting')], max_length=50, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('ended', 'ended'), ('scheduled', 'scheduled')], default='active', max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_recording_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('waiting_room_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('host_id', models.ForeignKey(db_column='Host_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_Meetings',
            },
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(blank=True, choices=[('text', 'text'), ('file', 'file')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_private', models.BooleanField(blank=True, default=False, null=True)),
                ('user_id', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('meeting_id', models.ForeignKey(db_column='Meeting_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_messages', to='core.meetings')),
            ],
            options={
                'db_table': 'tbl_Chat_Messages',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('join_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('host', 'host'), ('co-host', 'co-host'), ('participant', 'participant')], max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, editable=False, null=True)),
                ('engagement_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('meeting_id', models.ForeignKey(db_column='Meeting_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='core.meetings')),
                ('user_id', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_Participants',
            },
        ),
    ]
