# Generated by Django 5.0.14 on 2025-09-02 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='livekit_room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='livekit_room_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='end_meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(db_column='Meeting_ID', max_length=36)),
                ('user_id', models.CharField(db_column='User_ID', max_length=100)),
                ('popup_count', models.IntegerField(default=0)),
                ('detection_counts', models.TextField(default='0')),
                ('violation_start_times', models.TextField(default='{}')),
                ('total_detections', models.IntegerField(default=0)),
                ('attendance_penalty', models.FloatField(default=0.0)),
                ('session_active', models.BooleanField(default=False)),
                ('break_used', models.BooleanField(default=False)),
                ('violations', models.TextField(default='[]')),
                ('session_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_face_movement_time', models.FloatField(default=0.0)),
                ('inactivity_popup_shown', models.BooleanField(default=False)),
                ('last_popup_time', models.FloatField(default=0.0)),
                ('total_session_time', models.IntegerField(default=0)),
                ('active_participation_time', models.IntegerField(default=0)),
                ('violation_severity_score', models.FloatField(default=0.0)),
                ('frame_processing_count', models.IntegerField(default=0)),
                ('last_violation_type', models.CharField(blank=True, max_length=50)),
                ('continuous_violation_time', models.IntegerField(default=0)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('focus_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_Attendance_Sessions',
                'indexes': [models.Index(fields=['meeting_id'], name='tbl_Attenda_Meeting_49f92d_idx'), models.Index(fields=['user_id'], name='tbl_Attenda_User_ID_1c8e34_idx'), models.Index(fields=['session_active'], name='tbl_Attenda_session_f3b3e0_idx'), models.Index(fields=['created_at'], name='tbl_Attenda_created_9ef47b_idx')],
                'unique_together': {('meeting_id', 'user_id')},
            },
        ),
        migrations.DeleteModel(
            name='ChatMessages',
        ),
    ]
