# Generated by Django 5.0.14 on 2025-09-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meetings_livekit_room_name_meetings_livekit_room_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='break_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='break_sessions',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='current_break_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_currently_on_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='last_break_calculation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='max_break_time_allowed',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='total_break_time_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participants',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('InstantMeeting', 'InstantMeeting'), ('ScheduleMeeting', 'ScheduleMeeting'), ('CalendarMeeting', 'CalendarMeeting')], max_length=50, null=True),
        ),
    ]
