# CHANGE listening-ip, relay-ip, external-ip to your server's IP
listening-port=5349
listening-ip=192.168.48.201
relay-ip=192.168.48.201
external-ip=192.168.48.201
min-port=50000
max-port=60000
fingerprint
lt-cred-mech
user=imeetpro:imeetpro2026
realm=imeetpro
no-tls
no-dtls
log-file=/tmp/turnserver.log
simple-log
